name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Mono Build
        run: |
          chmod +x ./build.sh && ./build.sh

      - name: Markdown Check
        if: ${{ always() }}
        run: |
          sudo gem install mdl

          for file in *.md
          do
            mdl "$file"
          done
