name: CI

on:
  push:
    branches: [ multiplatform-ci ]
  pull_request:
    branches: [ multiplatform-ci ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-10.15, windows-2019 ]

    steps:
      - uses: actions/checkout@v2

      - name: Mono Build
        run: |
          function installCsCompiler()
          {
            if mono --version &> /dev/null
            then
              return
            fi
            
            case "$OSTYPE" in
              darwin*)
                brew install mono
                ;;
              msys)
                choco install mono -y
                ;;
            esac
          }

          installCsCompiler

          chmod +x build.sh && ./build.sh
        
      - name: Upload Artifacts
        if: $matrix.os == 'ubuntu-20.04'
        uses: actions/upload-artifact@v2
        with:
          name: program
          path: main.exe
          retention-days: 1
  
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Markdown Check
        run: |
          sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
          npm install -g markdownlint-cli
          markdownlint *.md
      - name: Shell Check
        if: always()
        run: |
          sudo apt-get install shellcheck
          shellcheck *.sh
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: program
      - name: CSharp Check
        if: always()
        run: |
          sudo apt update
          sudo apt-get install gendarme
          gendarme -- *.exe
