name: CI

on:
  push:
    branches: [ multiplatform-ci ]
  pull_request:
    branches: [ multiplatform-ci ]

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-10.15, windows-2019 ]

    steps:
      - uses: actions/checkout@v2

      - name: Mono Install
        run: |
          chmod +x ./build_init.sh && ./build_init.sh
      - name: Mono Build
        run: |
          chmod +x ./build.sh && ./build.sh
      - name: Linter Install
        run: |
          sudo chown -R $USER ~/.npm
          sudo chown -R $USER /usr/lib/node_modules
          sudo chown -R $USER /usr/local/lib/node_modules
          chmod +x ./analyze_init.sh && ./analyze_init.sh
      - name: Linter Check
        run: |
          if [[ "$OSTYPE" == "msys" ]]
          then
            temp="temp.txt"
            for file in *.sh
            do
              cat "$file" | tr -d '\r' > "$temp"
              cat "$temp" > "$file"
            done
            rm "$temp"
          fi
          chmod +x ./analyze.sh && ./analyze.sh
